Fixed error messages when downloading to include the podcast Name
It was

Downloading 3 episodes
System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)

Now it is

Downloading 3 episodes
Error in: Test Match Special How have Australia changed since sandpaper gate?
 System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)